### ISSUE TITLE
Use one queue per message class?

### ISSUE THREAD

**Issue by soyuka** [sroze/enqueue-bridge#8]
What's the reasoning behind using only one queue (defined by the environment)?

Then, I thought about a dx-friendlier configuration:

```
# enqueue_bridge:
messages:
    - App\Message\FooMessage: 'bar_queue_name'
    - App\Message\BarMessage: 'foo_queue_name'
```

This would set up the message classes to use `enqueue_bridge.sender`.

**Comment by sroze** [comment]
I don't get your idea 🤔 The routing of messages to the queues is done by Symfony's FrameworkBundle isn't it?

**Comment by soyuka** [comment]
This bridge is using only one queue defined by:

```yaml
enqueue_bridge:
    queue: "%env(ENQUEUE_BRIDGE_QUEUE_NAME)%"
```

In my framework I'm currently declaring:

```yaml
    messenger:
        routing:
            'App\Message\FooMessage': enqueue_bridge.sender
            'App\Message\BarMessage': enqueue_bridge.sender
```

My thought was to abstract the `messenger` framework declaration inside `enqueue_bridge`. On top of that, we could allow one queue per message class:

```yaml
enqueue_bridge:
    messages:   
        - App\Message\FooMessage: 'bar_queue_name'
        - App\Message\BarMessage: 'foo_queue_name'
```
